# Generated by Django 3.2.7 on 2021-11-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20211114_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='result',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
